In [33]:
import pandas as pd
import numpy as np

In [34]:
df=pd.read_json("/home/illahi/Desktop/script-bag-of-words.json")

In [35]:
df.tail()

episodeAlt  seasonNum  episodeNum                    episodeTitle  \
68       S8E2          8           2  A Knight of the Seven Kingdoms   
69       S8E3          8           3                  The Long Night   
70       S8E4          8           4          The Last of the Starks   
71       S8E5          8           5                       The Bells   
72       S8E6          8           6                 The Iron Throne   

                                                 text  
68  [{'name': 'Daenerys Targaryen', 'text': 'About...  
69  [{'name': 'Northman #1', 'text': 'Oi!'}, {'nam...  
70  [{'name': 'Jon Snow', 'text': 'And Everyone It...  
71  [{'name': 'Lord Varys', 'text': 'And? Come Not...  
72  [{'name': 'Tyrion Lannister', 'text': 'I'll fi...

In [36]:
df.iloc[-1]["text"]

[{'name': 'Tyrion Lannister', 'text': "I'll find later. you"},
 {'name': 'Jon Snow', 'text': "It's Let me men not safe. send some with you."},
 {'name': 'Tyrion Lannister', 'text': "I'm alone. going"},
 {'name': 'Grey Worm',
  'text': 'Daenerys I In Queen, Targaryen, die. name of one sentence the the to true you'},
 {'name': 'Jon Snow',
  'text': "Grey It's These Worm! are men over. prisoners."},
 {'name': 'Grey Worm',
  'text': "It Queen's are defeated. enemies is not over the until"},
 {'name': 'Davos Seaworth',
  'text': "How They're be? defeated do knees. more much on their them to want you"},
 {'name': 'Grey Worm', 'text': 'They are breathing.'},
 {'name': 'Davos Seaworth', 'text': 'Look We around friend. won. you,'},
 {'name': 'Grey Worm', 'text': "I commands, my not obey queen's yours."},
 {'name': 'Jon Snow', 'text': "And Queen's are commands? the what"},
 {'name': 'Grey Worm',
  'text': '"Kill Cersei Lannister." These They all are chose fight follow for free her. men. to who'}

In [37]:
dialogue={}
for ind,row in df.iterrows():
    for i in row['text']:
        if i['name'] in dialogue:
            dialogue[i["name"]]=dialogue[i["name"]]+i["text"]
        else:
            dialogue[i["name"]]=i["text"]+" "

In [38]:
len(dialogue)

817

In [39]:
dialogue.keys()

dict_keys(['Will', 'Waymar Royce', 'Gared', 'Jon Snow', 'Septa Mordane', 'Sansa Stark', 'Eddard Stark', 'Robb Stark', 'Rodrik Cassel', 'Catelyn Stark', 'Bran Stark', 'Theon Greyjoy', 'Jaime Lannister', 'Cersei Lannister', 'Maester Luwin', 'Arya Stark', 'Robert Baratheon', 'Tyrion Lannister', 'Ros', 'Viserys Targaryen', 'Daenerys Targaryen', 'Maid', 'Illyrio Mopatis', 'Benjen Stark', 'Stark Guard', 'Khal Drogo', 'Jorah Mormont', 'Sandor Clegane', 'Doreah', 'Irri', 'Joffrey Baratheon', 'Myrcella Baratheon', 'Catspaw Assassin', 'Jhiqui', 'Mycah', 'Lannister Soldier #1', 'Lannister Soldier #2', 'Jory Cassel', 'Lannister Soldier', 'Royal Steward', 'Lord Varys', 'Renly Baratheon', 'Petyr Baelish', 'Grand Maester Pycelle', 'Old Nan', "King's Landing Guard", 'Alliser Thorne', 'Jeor Mormont', 'Grenn', 'Pypar', 'Rast', 'Barristan Selmy', 'Lancel Lannister', 'Dothraki Rider', 'Rakharo', 'Yoren', 'Maester Aemon', 'Syrio Forel', 'Hodor', 'Samwell Tarly', 'Janos Slynt', 'Hugh Of The Vale', 'Tobho Mo

In [40]:
newdf=pd.DataFrame()
newdf['character']=dialogue.keys()
newdf['words']=dialogue.values()

In [41]:
newdf

character                                              words
0             Will  Easy, boy. I've I've Wildlings a a do ever in ...
1     Waymar Royce  One They're What a and another before d'you ea...
2            Gared  Wall. We back head should the to Our They We W...
3         Jon Snow  Father's Go on. watching. And mother. yourBran...
4    Septa Mordane  Fine Well always. as done. work, I Quite beaut...
..             ...                                                ...
812        Lord #1                     Aye. All Bran Broken! hail the
813        Lord #2                     Aye. All Bran Broken! hail the
814   Dornish Lord                     Aye. All Bran Broken! hail the
815        Lord #3                     Aye. All Bran Broken! hail the
816        Lord #4                     Aye. All Bran Broken! hail the

[817 rows x 2 columns]

In [45]:
# for ind,row in newdf.iterrows():
#     for i in row["words"]:
#         newdf["number"]=len(i.split())

In [51]:
# Assuming 'words' column contains lists of strings
newdf['number'] = newdf['words'].apply(lambda words: len(words.split()))


In [52]:
newdf

character                                              words  \
0             Will  Easy, boy. I've I've Wildlings a a do ever in ...   
1     Waymar Royce  One They're What a and another before d'you ea...   
2            Gared  Wall. We back head should the to Our They We W...   
3         Jon Snow  Father's Go on. watching. And mother. yourBran...   
4    Septa Mordane  Fine Well always. as done. work, I Quite beaut...   
..             ...                                                ...   
812        Lord #1                     Aye. All Bran Broken! hail the   
813        Lord #2                     Aye. All Bran Broken! hail the   
814   Dornish Lord                     Aye. All Bran Broken! hail the   
815        Lord #3                     Aye. All Bran Broken! hail the   
816        Lord #4                     Aye. All Bran Broken! hail the   

     no_of_words  number  
0            817     113  
1            817      94  
2            817      26  
3            817   11488  
4            817     290  
..           ...     ...  
812          817       6  
813          817       6  
814          817       6  
815          817       6  
816          817       6  

[817 rows x 4 columns]

In [55]:
newdf=newdf.sort_values("number",ascending=False)

In [66]:
newdf.sample(50)

character  \
661           Harry Strickland   
406       Night's Watch Man #3   
782      Lannister Soldier #23   
623         Archmaester Ebrose   
464                  Old Woman   
799     King's Landing Man #27   
66                       Bronn   
336                      Merry   
505       Night's Watch Ranger   
689                Northman #1   
239                  Silk King   
478           Merchant Captain   
683          Winterfell Man #8   
584             Ironborn Crowd   
287       Riverlands Traveller   
383                       Olly   
543             Moro's Wife #1   
90                        Joss   
160               Yara Greyjoy   
540                      Qhono   
537             Bolton Officer   
263  King's Landing Soldier #1   
97               Jaremy Rykker   
335          Prendahl Na Ghezn   
751        Winterfell Woman #5   
783      Lannister Soldier #24   
236            Ironborn Man #2   
666        Winterfell Smith #2   
596             Lyanna Mormont   
309                      Marei   
106          Night's Watch Man   
621                  Ned Umber   
590              Randyll Tarly   
458           Meereenese Crowd   
305          Craster's Wife #1   
765       King's Landing Child   
586              Rickard Stark   
565            Dothraki Matron   
470         Volantene Whore #3   
673      Winterfell Soldier #3   
491                      Ghita   
29                        Irri   
770      Lannister Soldier #19   
575                Khal Rhalko   
412              Adrack Humble   
215      King's Landing Man #1   
203         Reginald Lannister   
532  King's Landing Flasher #1   
746         Winterfell Man #17   
692        Northern Soldier #1   

                                                 words  no_of_words  number  
661  A Grace. Yes, Your died few in transit. Two th...          817      35  
406  Didn't I'd again. see think you Come Hold Hold...          817      28  
782                                   Ring bells! the           817       3  
623  A Ah, I Maester Mankind's The Weigh Weyland. c...          817     845  
464  I'll You a bowl bring hot must of to want wash...          817      54  
799                           Come Hurry Now! on! up!           817       5  
66   You can have my room. Nothing You Your a a a a...          817    4336  
336                                        I'm Merry.           817       2  
505                                   Watch bow! your           817       3  
689                                          Oi! Move!          817       2  
239  Begging It ago long threatening us. us? very w...          817      11  
478              Isle. Jaime. Sapphire Ser Tarth, The           817       6  
683                   Yes, sir. That's easy, isn't it?          817       6  
584  Aye! Aye!Aye!Aye!Aye!Aye!Aye!Yara! Yara! Yara!...          817      17  
287  Where are headed, then? you Riverrun. Staying ...          817      58  
383  Mother eat. it's says time to Potatoes.Yes. Ye...          817     233  
543  Chiorisi chandri maegi. tihi Zirisses hatif me...          817      25  
90   'em Riverlands, They They They When again. and...          817     133  
160  I I'm can heading take that there. way. you Or...          817    1699  
540  Ishish Mai anni inavvasi leyes leyes. majin me...          817      60  
537  Tell down! settle them to Bolton? Lady Where i...          817      25  
263  Get No! fool. up, you Yes.And The at gates. ga...          817      18  
97                                   Rangers me. with           817       3  
335  He's He's a a captain. lieutenant. not If Our ...          817      52  
751                      It's heavy, mind really you.           817       5  
783                                   Ring bells! the           817       3  
236  Prince Theon. Open gate! theQueen! You be not ...          817      26  
666                                Gendry? He's here.           817       3  
596  Bear Island. Welcom

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(stop_words='english')

In [65]:
embeddings=cv.fit_transform(newdf["words"]).toarray()

In [67]:
embeddings.shape

(817, 17102)

In [68]:
embeddings


array([[ 5,  1,  0, ...,  0,  0,  0],
       [ 3,  0,  0, ...,  0,  0,  0],
       [11,  0,  2, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0]])

In [69]:
embeddings=embeddings.astype("float64")


In [70]:
embeddings


array([[ 5.,  1.,  0., ...,  0.,  0.,  0.],
       [ 3.,  0.,  0., ...,  0.,  0.,  0.],
       [11.,  0.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [71]:
from sklearn.manifold import TSNE


In [73]:
tsne=TSNE(n_components=2,verbose=1,random_state=123)
z=tsne.fit_transform(embeddings)

[t-SNE] Computing 91 nearest neighbors...
[t-SNE] Indexed 817 samples in 0.022s...
[t-SNE] Computed neighbors for 817 samples in 1.787s...
[t-SNE] Computed conditional probabilities for sample 817 / 817
[t-SNE] Mean sigma: 0.000000
[t-SNE] KL divergence after 250 iterations with early exaggeration: 63.417610
[t-SNE] KL divergence after 1000 iterations: 1.340997


In [74]:
z.shape

(817, 2)

In [75]:

z

array([[21.432842 , 20.547808 ],
       [20.892807 , 20.317835 ],
       [21.180357 , 19.43447  ],
       ...,
       [-3.4110827, -2.1742918],
       [-2.834541 , -1.1875235],
       [-2.4938095, -1.0297425]], dtype=float32)

In [87]:

newdf['X']=z.T[0]
newdf['Y']=z.T[1]


In [88]:
newdf

character                                              words  \
17     Tyrion Lannister  It Mmh. Northern about girls. is say the they ...   
13     Cersei Lannister  And And Casterly One Rock. When about afraid. ...   
3              Jon Snow  Father's Go on. watching. And mother. yourBran...   
20   Daenerys Targaryen  We've a and anything. asked been for for guest...   
12      Jaime Lannister  As I It's brother, duty feel it's much. my sho...   
..                  ...                                                ...   
391     Great Master #1                                                      
402          Manservant                                                      
439           White Rat                                                      
474       Brothel Guard                                                      
432      Meereenese Man                                                      

     no_of_words  number          x          y          X          Y  
17           817   25924  21.432842  20.547808  21.432842  20.547808  
13           817   14294  20.892807  20.317835  20.892807  20.317835  
3            817   11488  21.180357  19.434469  21.180357  19.434469  
20           817   11202  19.815313  20.541019  19.815313  20.541019  
12           817   10823  20.750481  19.888023  20.750481  19.888023  
..           ...     ...        ...        ...        ...        ...  
391          817       0  -2.176098  -2.329128  -2.176098  -2.329128  
402          817       0  -1.778866  -3.729328  -1.778866  -3.729328  
439          817       0  -3.411083  -2.174292  -3.411083  -2.174292  
474          817       0  -2.834541  -1.187523  -2.834541  -1.187523  
432          817       0  -2.493809  -1.029742  -2.493809  -1.029742  

[817 rows x 8 columns]

In [81]:
pip install plotly

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 4.0 MB/s eta 0:00:000m eta 0:00:010:01:01
Note: you may need to restart the kernel to use updated packages.


In [103]:
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
a=newdf.head(25)

In [107]:
fig=px.scatter(newdf.head(25),x='X',y='Y',color="character")

# plt.scatter(a['X'],a['y'],label=a["character"])
# sns.scatterplot(a,label=a["character"])
# plt.label()

In [108]:
fig.show()